compileMac:
	javac -Xlint -cp ../lib/postgresql-42.3.1.jar:. Ap3.java

runMac:
	java -cp ../lib/postgresql-42.3.1.jar:. Ap3

compileWin:
	javac -cp ../lib/postgresql-42.3.1.jar;. Ap3.java

runWin:
	java -cp ../lib/postgresql-42.3.1.jar;. Ap3

clean:
	rm -rf *.class
